### ISSUE TITLE
Poor auth implementation

### ISSUE THREAD

**Issue by tpetrone** [rafaelangical/library-app#10]
Application is not secure since an unauthorized user can change the URL in the address bar and gain access to "protected" routes

**Comment by rafaelangical** [comment]
#resolved

**Comment by tpetrone** [comment]
Accessing a protected route, without being authenticated, result in application breaking.

<img width="1275" alt="screen shot 2018-06-19 at 18 16 14" src="https://user-images.githubusercontent.com/6620216/41624733-e6ff187a-73ec-11e8-898f-d95f77a6e1d8.png">

Suggest **reopening**

**Comment by tpetrone** [comment]
@rafaelangical you should reopen this

**Comment by tpetrone** [comment]
@rafaelangical did you give up?

**Comment by rafaelangical** [comment]
#resolved
