### ISSUE TITLE
Error on Authenticate user

### ISSUE THREAD

**Issue by rafaelangical** [rafaelangical/library-app#9]
Error during authenticate returning error " Error: The Torii adapter must implement `open` for a session to be opened " on console.

**Comment by rafaelangical** [comment]
@tpetrone

**Comment by rafaelangical** [comment]
![captura de tela de 2018-06-14 22-20-27](https://user-images.githubusercontent.com/20307803/41445850-aa2ccda2-7022-11e8-829b-c65c200395d2.png)

**Comment by rafaelangical** [comment]
To test use.
login: teste@teste.com
password: teste123

**Comment by tpetrone** [comment]
@rafaelangical you are not implementing a `torii-adapter` which is a crucial step configuring your session management

**Comment by tpetrone** [comment]
@rafaelangical mind closing resolved issues

**Comment by rafaelangical** [comment]
#closed
